package dev.jdtech.jellyfin.player.session.voice

data class PlayerStateSnapshot(
    val isPlaying: Boolean = false,
    val positionSeconds: Long = 0,
    val durationSeconds: Long = 0,
    val controlsVisible: Boolean = false,
    val currentItemTitle: String = "",
    val currentOverview: String = "",
    val currentSeriesName: String? = null,
    val currentSeasonNumber: Int? = null,
    val currentEpisodeNumber: Int? = null,
    val currentSegmentType: String? = null,
    val currentChapterName: String? = null,
    val nextEpisodeTitle: String? = null,
    val currentGenres: List<String> = emptyList(),
    val castNames: List<String> = emptyList(),
    val audioTrackNames: List<String> = emptyList(),
    val subtitleTrackNames: List<String> = emptyList(),
    val chapterNames: List<String> = emptyList(),
    val currentAudioTrack: String? = null,
    val currentSubtitleTrack: String? = null,
    val currentAudioLanguageCode: String? = null,
    val currentSubtitleLanguageCode: String? = null,
    val inVoiceSearch: Boolean = false,
    val voiceSearchQuery: String? = null,
    val voiceSearchResultsCount: Int = 0,
    val syncPlayActive: Boolean = false,
    val syncPlayGroupName: String? = null,
    val syncPlayParticipantNames: List<String> = emptyList(),
    val passthroughEnabled: Boolean = false,
)
